name: Github Action Demo
on: push
jobs:
  Example-Actions-Job:
    name: Exploring Actions
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a $${{ github.event_name }} event"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "Your repo has been copied"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
      - name: Display Dotnet
        run: dotnet --version
  Second-job:
    name: Second job
    runs-on: ubuntu-latest
    needs: Example-Actions-Job
    steps:
      - run: "The is new job"
